# Generated by Django 5.2 on 2025-04-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_purchaseorder_date_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='stage',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
